#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/bitmap
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/access/bitmap
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = bitmap.o bitmapattutil.o bitmapinsert.o bitmappages.o \
    bitmapsearch.o bitmaputil.o bitmapxlog.o 

include $(top_srcdir)/src/backend/common.mk
